#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

from cmk.base.config import special_agent_info
import shlex

def agent_rdspostgres_arguments(params, hostname, ipaddress):
    # User, Password
    return "%s %s %s" % ( shlex.quote(ipaddress), shlex.quote(params["username"]), shlex.quote(params["password"]) )

special_agent_info['rdspostgres'] = agent_rdspostgres_arguments
