#!/bin/bash

#This script, designed for CheckMK, check remaining SMS through Skebby API. This check is compatible with CheckMK.

#CRIT < 10
#WARN tra 10 e 20 non compreso
#OK > 20
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
SESSION=$(curl --silent -XGET "https://api.skebby.it/API/v1.0/REST/login?username=xxxx&password=xxxxx")
USER_KEY=$(echo $SESSION | cut -d ";" -f 1)
SESSION_KEY=$(echo $SESSION | cut -d ";" -f 2)


RESULT=$(curl --silent -XGET 'https://api.skebby.it/API/v1.0/REST/status' -H 'Content-Type: application/json' -H 'user_key: '$USER_KEY'' -H 'Session_key: '$SESSION_KEY'')
RESULT=$(echo $RESULT | jq '.sms[] | select(.type=="TI").quantity')


if [ "$RESULT" -ge 20 ]; then
        echo "OK - Credito Skebby disponibile di $RESULT SMS (di tipo Basic). | SMS=$RESULT"
        exitstatus=$STATE_OK
        exit $exitstatus
elif  [ "$RESULT" -lt 10 ]; then
        echo "CRIT - Credito Skebby disponibile di $RESULT SMS (di tipo Basic). | SMS=$RESULT"
        exitstatus=$STATE_CRITICAL
        exit $exitstatus
else
        echo "WARN - Credito Skebby disponibile di $RESULT SMS (di tipo Basic). | SMS=$RESULT"
        exitstatus=$STATE_WARNING
        exit $exitstatus
fi